@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzY0OTQ0MTV9.KBOqhShzgf90HdQ859sF6qBy33oJvsvncdD-bFADWJo

###User Create
post http://localhost:3000/users
Content-Type: application/json 

{
  "name": "test",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password",
  "image_url": ""
}

###User Show
GET http://localhost:3000/user/1

###Session Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password"
}

###Index
get http://localhost:3000/all

###Show
GET http://localhost:3000/anime/5.json
Authorization: Bearer {{jwt}}


###Index Favorites
GET http://localhost:3000/favorites.json
Authorization: Bearer {{jwt}}

###Add Favorites
POST http://localhost:3000/favorites/add
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "item_id": "6"
}

###Delete Favorites
DELETE http://localhost:3000/favorites/16
Authorization: Bearer {{jwt}}
